apiVersion: apps/v1
kind: Deployment
metadata:
  name: hr-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hr-api
  template:
    metadata:
      labels:
        app: hr-api
    spec:
      containers:
      - name: hr-api
        image: backend-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: ConnectionStrings__DefaultConnection
          value: Host=postgres;Port=5432;Database=hrdb;Username=postgres;Password=postgres

        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"