version: '3.9'

services:

  postgres:
    image: postgres:16
    container_name: hr_postgres
    restart: always
    environment:
      POSTGRES_DB: hrdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: HR.API/Dockerfile
    container_name: hr_api
    depends_on:
      - postgres
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Default: Host=postgres;Port=5432;Database=hrdb;Username=postgres;Password=postgres
    ports:
      - "8080:8080"

volumes:
  postgres_data: